name: aixinwu-scheduler

on:
  push:
    paths:
      - aixinwu-sign/**
      - .github/workflows/aixinwu-scheduler.yml
  schedule:
    - cron: "0 8-23/12 * * *" # 每天跑多次，每隔六小时

jobs:
  aixinwu:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17" # The Go version to download (if necessary) and use.
      - run: go run aixinwu-sign/main.go -auth "${{ secrets.AUTHORIZATION}}"
