name: scu-micro-services

on:
  push:
    paths:
      - scu-micro-services/**
      - .github/workflows/scu-micro-services.yml
  # schedule:
  #   - cron: "0 16 * * *"  # 16 点 => 东八区的 0 点
  #   - cron: "58 15 * * *"  # 15:58 => 23:58
jobs:
  scu:
    runs-on: "ubuntu-latest"
    env:
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EAI_SESS: ${{ secrets.EAI_SESS }}
      UUKEY: ${{ secrets.UUKEY }}
      TO: ${{ secrets.TO }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - run: go run scu-micro-services/main.go -eai $EAI_SESS -uukey $UUKEY -eu $EMAIL_USERNAME -ep $EMAIL_PASSWORD -to $TO
